### ISSUE TITLE
Request: Make internal links clickable

### ISSUE THREAD

**Issue by Narsail** [yildbs/obsidian-harada-method-plugin#2]
Currently, internal links can't be clicked, so I cannot navigate from the Harada to the linked note. 

It would be very helpful to make them clickable, as I can incorporate them better into my workflow.

Btw, great idea to add the Harada method as a plugin 👍

**Comment by yildbs** [comment]
Implemented related to internal link and released. You can use version 1.0.6.
- [[path_to_md]]
- [[path_to_md|Title]]     ->  split by " | " pipe character


You can change the title of the internal link using title.
Thank you for your kind comments.
