### ISSUE TITLE
Q: Request for recommended material

### ISSUE THREAD

**Issue by replete** [yildbs/obsidian-harada-method-plugin#4]
Hi there!

I stumbled on your plugin through the community plugin UI in obsidian, and I've been watching videos about the method for a couple of hours. I am super keen to implement this myself as this is something I've been trying to make sense of recently - very pleased to find your plugin and discover this approach.

I'm trying to piece together the system from random youtube videos so if you have any advice I'd be really grateful!

Kind Regards,

Phil

**Comment by yildbs** [comment]
Hello! 
I'm glad I can help. How can I help you? Curious about what you need to know to implement this plugin yourself?
Thank you! 😀

**Comment by replete** [comment]
I have got the plugin working, thank you very much.
I will now try to find resources in which to learn the Harada Method and do my best to find an obsidian workflow - I'm already using daily notes so it should not be too difficult.

GOAL: Implement the Harada Method in Obsidian

Thanks for this plugin, I am very glad to discover this method.
