### ISSUE TITLE
Give more information what the "harada method" is in the README

### ISSUE THREAD

**Issue by finn-matti** [yildbs/obsidian-harada-method-plugin#5]
I think a link to e.g. a trustworthy blog post would be helpful here. If you search for "harada method" you'll find lots of trash, which makes it less likely for people to try out your plugin.

**Comment by yildbs** [comment]
Thank you for your kind words. It would be nice to provide a more detailed explanation of the harada method. So I added an intuitive example. Thank you for your attention. 😁
