### ISSUE TITLE
Colors in options are not working

### ISSUE THREAD

**Issue by sambody** [yildbs/obsidian-harada-method-plugin#6]
I have changed the colors in the options, but those new colors, although they are saved, are not reflected in the actual Harada grid. The preview shows the original colors, not the new colors defined in the options. Even after a restart. Could you look into it? Thanks.

**Comment by yildbs** [comment]
It is not reproducible in my environment 😿. Could you try deleting the plugin and reinstalling it?

**Comment by sambody** [comment]
Hello. Deleting and reinstalling the plugin made it work. So all is well. Thanks!
