### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by tjharr2** [yildbs/obsidian-harada-method-plugin#7]
Hi, I love your Harada goal graphic idea in obsidian. Unfortunately, despite following your instructions and even trying numerous possible alterations, I can’t get it the graphic to result from my code formatting. Can you see what I’m doing wrong?

Here’s what results from the code:
![Screenshot 2023-07-25 at 10 32 13 PM png](https://github.com/yildbs/obsidian-harada-method-plugin/assets/140573469/b6f8b1ed-2939-434c-b4ba-73d386cbda38)

```harada
Main goal
	Key plan 1
		Action 1
		Action 2
		Action 3
		Action 4
		Action 5
		Action 6
	Key plan 2
		Action 1
		Action 2
		Action 3
		Action 4
		Action 5
		Action 6
	Key plan 3
		Action 1
		Action 2
		Action 3
		Action 4
		Action 5
		Action 6
	Key plan 4
		Action 1
		Action 2
		Action 3
		Action 4
		Action 5
		Action 6
	Key plan 5
		Action 1
		Action 2
		Action 3
		Action 4
		Action 5
		Action 6
	Key plan 6
		Action 1
		Action 2
		Action 3
		Action 4
		Action 5
		Action 6
	Key plan 7
		Action 1
		Action 2
		Action 3
		Action 4
		Action 5
		Action 6
	Key plan 8
		Action 1
		Action 2
		Action 3
		Action 4
		Action 5
		Action 6
```

**Comment by tjharr2** [comment]
I include the three code opener ``` at the beginning and end too but they didn’t show in my first message:

![Screenshot 2023-07-25 at 10 35 58 PM png](https://github.com/yildbs/obsidian-harada-method-plugin/assets/140573469/18dcad6b-df83-4070-b8b0-9e206bc0cec8)

**Comment by ricardonevesmusic** [comment]
I guess this will make it work:

```harada
main goal
  key plan 1
    action 1
    action 2
    action 3
    action 4
    action 5
    action 6
    action 7
    action 8
    ...
  key plan 2
    action 1
    action 2
    action 3
    action 4
    action 5
    action 6
    action 7
    action 8
    ...
  key plan 3
    action 1
    action 2
    action 3
    action 4
    action 5
    action 6
    action 7
    action 8
    ...
  key plan 4
    action 1
    action 2
    action 3
    action 4
    action 5
    action 6
    action 7
    action 8
    ...
  key plan 5
    action 1
    action 2
    action 3
    action 4
    action 5
    action 6
    action 7
    action 8
    ...
  key plan 6
    action 1
    action 2
    action 3
    action 4
    action 5
    action 6
    action 7
    action 8
    ...
  key plan 7
    action 1
    action 2
    action 3
    action 4
    action 5
    action 6
    action 7
    action 8
    ...
  key plan 8
    action 1
    action 2
    action 3
    action 4
    action 5
    action 6
    action 7
    action 8
    ...
 ```
(make sure to always separate/press the space bar 2 times between each thing/goal; example: main goal (no space in beginning of the word) → key plan (always press the space bar 2 times or leave 2 empty/blank spaces in the beginning of the word) • same thing for the action items/lists: always leave 2 blank spaces in the beginning of the word)

[harada example.txt](https://github.com/yildbs/obsidian-harada-method-plugin/files/12388384/harada.example.txt)

main goal → leave no blank spaces in the beginning of the word
  key plan 1 → add/leave 2 blank spaces in the beginning of the word
    action 1 → add/leave 2 blank spaces in the beginning of the word (it's either 2 or 4 blank spaces depending on whether you're using the sentence "main goal" as a reference or the sentence "key plan")

I've included a text file with the code (if it's hard to understand what I'm saying/explaining, just copy the code and change the words to match your personal/specific goals/needs).

Yeah, I guess that's it.

Hope this helps.

**Comment by tjharr2** [comment]
Thanks! Working now!__Timothy J. Harrisc: (513) 446-7662On Aug 20, 2023, at 10:55 AM, ricardonevesmusic ***@***.***> wrote:﻿
I guess this will make it work:
main goal
  key plan 1
    action 1
    action 2
    action 3
    action 4
    action 5
    action 6
    action 7
    action 8
    ...
  key plan 2
    action 1
    action 2
    action 3
    action 4
    action 5
    action 6
    action 7
    action 8
    ...
  key plan 3
    action 1
    action 2
    action 3
    action 4
    action 5
    action 6
    action 7
    action 8
    ...
  key plan 4
    action 1
    action 2
    action 3
    action 4
    action 5
    action 6
    action 7
    action 8
    ...
  key plan 5
    action 1
    action 2
    action 3
    action 4
    action 5
    action 6
    action 7
    action 8
    ...
  key plan 6
    action 1
    action 2
    action 3
    action 4
    action 5
    action 6
    action 7
    action 8
    ...
  key plan 7
    action 1
    action 2
    action 3
    action 4
    action 5
    action 6
    action 7
    action 8
    ...
  key plan 8
    action 1
    action 2
    action 3
    action 4
    action 5
    action 6
    action 7
    action 8
    ...

(make sure to always separate/press the space bar 2 times between each thing/goal; example: main goal (no space in beginning of the word) → key plan (always press the space bar 2 times or leave 2 empty/blank spaces in the beginning of the word) • same thing for the action items/lists: always leave 2 blank spaces in the beginning of the word)
harada example.txt
main goal → leave no blank spaces in the beginning of the word
key plan 1 → add/leave 2 blank spaces in the beginning of the word
action 1 → add/leave 2 blank spaces in the beginning of the word (it's either 2 or 4 blank spaces depending on whether you're using the sentence "main goal" as a reference or the sentence "key plan")
I've included a text file with the code (if it's hard to understand what I'm saying/explaining, just copy the code and change the words to match your personal/specific goals/needs).
Yeah, I guess that's it.
Hope this helps.

**Comment by yildbs** [comment]
You need to use 2 space characters, not tab
I'm glad it's resolved :)
